### ISSUE TITLE
Error on Api-Details

### ISSUE THREAD

**Issue by kevinvenclovas** [DalSoft/DalSoft.WebApi.HelpPage#9]
Why i get this error when i open the api details -> The object reference was not set to an object instance

![image](https://user-images.githubusercontent.com/7681603/53941159-aa305d80-40b7-11e9-83f0-8f76eb80bcd6.png)

![image](https://user-images.githubusercontent.com/7681603/53941175-b87e7980-40b7-11e9-9fea-16cf9665f64b.png)

I Installed the nuget and added the line to my OwIn Startup

![image](https://user-images.githubusercontent.com/7681603/53941251-efed2600-40b7-11e9-89cf-a251d007a97e.png)

**Comment by DalSoft** [comment]
Hi, 

A guess would be you didn't enable XML comments example how to do this can. Be found here https://github.com/DalSoft/DalSoft.WebApi.HelpPage/blob/master/README.md

If that doesn't work let me know

**Comment by kevinvenclovas** [comment]
I added this befor.

![image](https://user-images.githubusercontent.com/7681603/53944328-6f322800-40bf-11e9-90b6-099512ff509b.png)

Here is on of my Comment:

![image](https://user-images.githubusercontent.com/7681603/53944596-04cdb780-40c0-11e9-8d66-0f0ee241fa62.png)

All works fine befor i added owin

**Comment by DalSoft** [comment]
This should work, would you be ok to allow me access to your code and I'll take a look at what's going on.

**Comment by kevinvenclovas** [comment]
Yes, you can find my code here https://github.com/Kshopper93/C--Owin-Help-Page-Error

**Comment by kevinvenclovas** [comment]
@DalSoft did you have found the issue?

**Comment by DalSoft** [comment]
@Kshopper93 It's been a while since I've have done anything non .NET Core, and I had a bit of trouble getting your repo working on my machine. There seems to be a lot going on in your project so I just copied your controllers and models to see if they generate the help pages correctly and they do.

Here is my repo with working help pages using your controllers and models: https://github.com/DalSoft/DalSoft.WebApi.HelpPage.Issue9

So it's not your model or controller code causing the issue, it's likely to be configuration or middleware causing the issue.

All I can suggest is start with just controllers and models code as well check that the help page works, and then start adding the middleware and extra settings one by one until you get the issue. Once you know what is causing the issue let me know and I'll try and help you further.

**Comment by kevinvenclovas** [comment]
FOund my problem but i don't know how solve this problem. When i remove the url apiversion than all worls fine. -> https://github.com/Microsoft/aspnet-api-versioning.

**Comment by kevinvenclovas** [comment]
This part in the controller routing is the issue -> v{version:apiVersion}

**Comment by DalSoft** [comment]
Ok I know what the problem is now aspnet-api-versioning requires you to add it's Versioned API Explorer to pick up the version routes in the API Explorer.

Add the nuget package:
`Microsoft.AspNet.WebApi.Versioning`
Then add to your startup:
```cs
config.AddApiVersioning();
config.AddVersionedApiExplorer( o => o.GroupNameFormat = "'v'VVV" );
```
https://github.com/Microsoft/aspnet-api-versioning/wiki/API-Documentation#aspnet-web-api

**Comment by DalSoft** [comment]
Solution found re-open if this is still an issue.
